### ISSUE TITLE
Comparisons need unit tests

### ISSUE THREAD

**Issue by mnaberez** [mnaberez/py65#24]
These instructions are missing unit tests:
- cmp
- cpx
- cpy

**Comment by scotws** [comment]
Is this still open? The devices in `py65/py65/tests/devices` seem to have only **CMP (nn,X)** and **CMP (nn),Y** if I understand the directory structure correctly.

**Comment by mnaberez** [comment]
Yes, tests for these are still needed.  There are only two tests and those are for the page wrapping bugs.  The comparison operations themselves are still untested.

**Comment by scotws** [comment]
Okay, I can take a look at that, I need a deeper dive into the comparison stuff anyway ...

**Comment by mnaberez** [comment]
That would be great, thanks!

**Comment by mnaberez** [comment]
Fixed in #52.
