### ISSUE TITLE
py65mon - assemble command - Can't convert 'bytes' object to str implicitly

### ISSUE THREAD

**Issue by mstram** [mnaberez/py65#27]
After entering 'a' for the assembler in py65mon, pressing any key gives :

Error: <class 'TypeError'>, 
Can't convert 'bytes' object to str implicitly: file: 
d:\python34\lib\site-packages\py65-0.20-py3.4.egg\py65\utils\console.py line: 92

Python 3.4.2  - Win Xp sp3 

Py65-0.20 from :
https://pypi.python.org/packages/source/p/py65/py65-0.20.zip#md5=55621b8475fa92c18befe3139b2d5b88

**Comment by mnaberez** [comment]
0.21 has been released with this fix.  Thanks for reporting it.
