### ISSUE TITLE
Taliforth project run  :  unsupported operand type(s) for &=: 'float' and 'int':

### ISSUE THREAD

**Issue by mstram** [mnaberez/py65#28]
Hi, thanks for the last fix, a(ssemble is working now ;)

I'm trying to run https://github.com/scotws/TaliForth on the same environment as my last report.

I've assembled it with  Ophis version 2.1 , clean no errors.

When I run it with : py65mon --mpu 65C02 -r ophis.bin I'm getting :

Error: <class 'TypeError'>, unsupported operand type(s) for &=: 'float' and 'int': file: d:\pyt
hon34\lib\site-packages\py65-0.21-py3.4.egg\py65\monitor.py line: 680

It's a tiny project (~800K), but if you just want the win32 binary I've uploaded it into my fork of the Taliforth project :+1: 

https://github.com/mstram/TaliForth/blob/master/ophis.bin.run

**Comment by mnaberez** [comment]
0.22 has been released with this fix.  Thank you!
