### ISSUE TITLE
'charmap' codec can't encode character '\xc3' - running taliforth

### ISSUE THREAD

**Issue by mstram** [mnaberez/py65#29]
Running the same taliforth I mentioned in my previous issue.

While this might not be specific to py65, the error only appeared after the fix to my last issue.

Since I'm only a casual Python user, I have no idea what the error means, but it turns up a lot hits on google.

I will also post an issue on the taliforth repo.

Booting Kernel for the Error: 
<class 'UnicodeEncodeError'>, 'charmap' codec can't encode character '\xc3' in position 0: character maps to <undefined>: file: d:\python34\lib\encodings\cp437.py line:

**Comment by mnaberez** [comment]
0.23 has been released with a workaround for this issue.

**Comment by mstram** [comment]
Thanks very much !
