### ISSUE TITLE
Where is utils/hexdump.py actually used?

### ISSUE THREAD

**Issue by scotws** [mnaberez/py65#37]
I might be missing something here, but after various grep sittings to find out what part of the code actually uses utils/hexdump.py I'm coming up blank (except of course of the tests). Is this a helper program for operating systems that don't have a built-in hexdump application like Linux? If not, can't we just delete it? Again, sorry if I'm missing something here.

**Comment by mnaberez** [comment]
> Is this a helper program for operating systems that don't have a built-in hexdump application like Linux?

At one point, I was given some hex listings and needed a way to load them into Py65.  That is what this code does (see [this example](https://github.com/mnaberez/py65/blob/1.0.0/py65/tests/utils/test_hexdump.py#L94-L98)).

> If not, can't we just delete it?

I haven't used it in quite some time, so I think it would be fine to delete it.
