### ISSUE TITLE
New release needed for pip users?

### ISSUE THREAD

**Issue by BigEd** [mnaberez/py65#42]
Over in issue #40 the TaliForth team updated their code to get a better than 10x speed gain and remove a dependency - to do that, they needed a newer py65 than the one installed with pip3 (see issue #41, now also fixed.)

@mnaberez it sounds like the py65 available by pip is ready for an update - time to consider a new release?

**Comment by mnaberez** [comment]
https://pypi.org/project/py65/1.1.0/

**Comment by SamCoVT** [comment]
Thanks, with double thanks to whomever added the getc and putc callbacks.  Those work great with the testing being done over at the TaliForth2 project.
