### ISSUE TITLE
On Windows, the -l (load) option can't handle paths with backslashes in them

### ISSUE THREAD

**Issue by SamCoVT** [mnaberez/py65#49]
This is problematic as Windows uses backslash to separate folders.  Interestingly, the -r option works fine. 
 The -l option will work if you escape all of the backslashes on the command line, like: 
`-l c:\\folder\\file.bin`.
See the #48 discussion on 2018-11-08 (search for "do_load") for a possible fix.

**Comment by mnaberez** [comment]
Fixed in #50
