### ISSUE TITLE
The docs imply this is a 6502 monitor app, not a library.

### ISSUE THREAD

**Issue by carlsmith** [mnaberez/py65#61]
The docs only explain how to use the monitor, with no mention of using `py65` as a library. There doesn't seem to be any (Python) examples or API docs or anything?? Do we just read the source?

**Comment by mnaberez** [comment]
It may be possible to use it as a library from another program.  The [full source code](https://github.com/mnaberez/py65) is available on GitHub.  Please use the source to evaluate whether it might be suitable for your application.

**Comment by BigEd** [comment]
This post by 'cjs' on the 6502 forums may be a good lead - start a new topic and you'll get help!
http://forum.6502.org/viewtopic.php?p=73564#p73564
