### ISSUE TITLE
How to run the example programs?

### ISSUE THREAD

**Issue by AmalIrfan** [mnaberez/py65#62]
How to run the example programs provided in examples dir?

**Comment by AmalIrfan** [comment]
I have accesdentanly ran the ehbasuc.bin, it looks wierd, I haven't used a BASIC machine so it might be me. Could any one tell what all I can do with it?

**Comment by AmalIrfan** [comment]
what does this mean
```6502 EhBASIC [C]old/[W]arm ?
Memory size ? $FFFF```
And what is the syntax of this language?

**Comment by BigEd** [comment]
There's an EhBasic guide here
http://www.sunrise-ev.com/photos/6502/EhBASIC-manual.pdf

I think Memory Size needs to be the amount of free memory, or an empty line. Try 16000. It's possible the memory test doesn't work well in py65.

Once you get the prompt, it's a Basic much like Microsoft's 6502 Basic.
