### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by nbarger** [mnaberez/py65#68]
Hello. I am wanting to do some experimentation with the CPUs individually without the monitor, mostly to make a computer or some sort of testing device with the "hardware" written in python. To see the api for it, however, I have to open the source code to see the classes and such.

I'm requesting a documentation for the api, so that other people don't have to search through the code to use stuff. If it is needed, I'll be willing to create the documentation.

Thanks.

**Comment by mnaberez** [comment]
I'm not going to add more documentation to this project, sorry.  I do not recommend trying to use this software without reading the source code, and enabling people to do that is not a goal of the project.  There are a lot of 6502 emulators out there.  I suggest that you choose another one that already has the level of documentation you're looking for.
