### ISSUE TITLE
pip install -U py65 installs old version

### ISSUE THREAD

**Issue by bjchapm** [mnaberez/py65#71]
`python3 -m pip install -U py65` installs an older version of the code. It's version 1.1.0, which doesn't have the [cut/paste fixes and other enhancements](https://github.com/mnaberez/py65/pull/48).

Could the latest version be submitted to PyPi?

As a workaround, I cloned the repo and copied the py65 folder from within the project folder into the site-packages folder for the local Python 3.11.

Best wishes, Ben

**Comment by 0cjs** [comment]
The version 1.1.0 I'm getting from PyPi is also giving me the following warnings:

```
.build/virtualenv/lib/python3.9/site-packages/pkg_resources/__init__.py:121
  /home/cjs/co/public/gh/0cjs/8bitdev/.build/virtualenv/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

.build/virtualenv/lib/python3.9/site-packages/py65/__init__.py:3
  /home/cjs/co/public/gh/0cjs/8bitdev/.build/virtualenv/lib/python3.9/site-packages/py65/__init__.py:3: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('py65')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    __import__('pkg_resources').declare_namespace(__name__)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

I'm guessing a newer version of py65 will fix this, so yes, it would be nice to get the PiPy version updated.

**Comment by mnaberez** [comment]
> ``` warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)```

This should be fixed by 7b9a7dea7061274d603b6a496e895daba2c0b136.

**Comment by 0cjs** [comment]
Sadly, I'm still even today getting version 1.1.0 from `pip install py65`. Can PyPI be updated?

**Comment by mnaberez** [comment]
Please don't open duplicate issues, this issue is still open.  I'm aware of the request and will close the issue when a new release is published.

**Comment by mnaberez** [comment]
[Py65 1.2.0](https://pypi.org/project/py65/1.2.0/#files)
